version: '3.8'

services:
  web:
    build: ./app
    command: daphne -b 0.0.0.0 -p 8000 VirtualMarket.asgi:application
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    links:
      - redis
    

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    image: redis
    command: redis-server
    ports:
      - '6379'

 
volumes:
  static_volume: