version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn VirtualMarket.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - redis

  channels:
    build: ./app
    command: daphne -b 0.0.0.0 -p 8001 VirtualMarket.asgi:application
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8001
    env_file:
      - ./.env

### Redis image ##
  redis:
    image: "redis:alpine"

  
### Celery workers ###
  celery_worker:
    build: ./app
    command: celery -A VirtualMarket worker -l info
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env
    depends_on:
      - redis


  celery_beat_worker:
    build: ./app
    command: celery -A VirtualMarket beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env
    depends_on:
      - redis
      

  ### NGINX reverse proxy server
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - channels

 
volumes:
  static_volume: