version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn VirtualMarket.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev

  channels:
    build: ./app
    command: daphne -b 0.0.0.0 -p 8001 VirtualMarket.asgi:application
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8001
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
      - channels

 
volumes:
  static_volume: