# Generated by Django 3.2.7 on 2021-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirMarket_CS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Finance_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
