# Generated by Django 3.2.7 on 2021-11-23 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VirMarket_CS', '0002_user_finance_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_finance_history',
            name='User_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
