# Generated by Django 3.2.7 on 2021-12-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirMarket_CS', '0003_user_finance_history_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('User_Admin', 'Has access to the entire application'), ('Base_User', 'Has basic access to the application')],
                'managed': False,
            },
        ),
    ]
