# Generated by Django 3.2.7 on 2021-12-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirMarket_CS', '0005_alter_user_roles_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='newstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField()),
                ('mac', models.IntegerField()),
                ('iphone', models.IntegerField()),
                ('android', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
    ]
