# Generated by Django 3.2.7 on 2021-09-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirMarket_CS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
