# Generated by Django 3.2.7 on 2021-09-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirMarket_CS', '0003_stocks_transactions_user_finances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
